name = "deleteapi"
main = "src/index.js"
compatibility_date = "2022-10-02"
kv_namespaces=[
    { binding = "productdetail", id = "e1cf2dd6d2a941b5aab6f0baea2473b0" }
]
[[r2_buckets]]
binding = "productimage"
bucket_name = "productimage"

